name: cnpmcore-web

volumes:
  cnpm-storage:

networks:
  cnpm-network:
    name: cnpm-network
    external: true

services:
  web:
    image: cnpmcore:latest
    restart: always
    environment:
      CNPMCORE_CONFIG_SOURCE_REGISTRY: ${CNPMCORE_CONFIG_SOURCE_REGISTRY:-https://registry.npmmirror.com}
      CNPMCORE_CONFIG_SOURCE_REGISTRY_IS_CNPM: ${CNPMCORE_CONFIG_SOURCE_REGISTRY_IS_CNPM:-true}
      CNPMCORE_CONFIG_REGISTRY: ${CNPMCORE_CONFIG_REGISTRY:-http://127.0.0.1:7001}
      CNPMCORE_CONFIG_ENABLE_WEB_AUTHN: ${CNPMCORE_CONFIG_ENABLE_WEB_AUTHN:-true}

      CNPMCORE_DATABASE_TYPE: ${CNPMCORE_DATABASE_TYPE:-MySQL}
      CNPMCORE_DATABASE_NAME: ${CNPMCORE_DATABASE_NAME:-cnpmcore}
      CNPMCORE_DATABASE_HOST: ${CNPMCORE_DATABASE_HOST:-127.0.0.1}
      CNPMCORE_DATABASE_PORT: ${CNPMCORE_DATABASE_PORT:-3306}
      CNPMCORE_DATABASE_USER: ${CNPMCORE_DATABASE_USER:-root}
      CNPMCORE_DATABASE_PASSWORD: ${CNPMCORE_DATABASE_PASSWORD:-}

      CNPMCORE_REDIS_HOST: ${CNPMCORE_REDIS_HOST:-127.0.0.1}
      CNPMCORE_REDIS_PORT: ${CNPMCORE_REDIS_PORT:-6379}
      CNPMCORE_REDIS_PASSWORD: ${CNPMCORE_REDIS_PASSWORD:-}
      CNPMCORE_REDIS_DB: ${CNPMCORE_REDIS_DB:-0}

      CNPMCORE_DATA_DIR: ${CNPMCORE_DATA_DIR:-}
      CNPMCORE_LOG_DIR: ${CNPMCORE_LOG_DIR:-}

      CNPMCORE_NFS_TYPE: ${CNPMCORE_NFS_TYPE:-local}
      CNPMCORE_NFS_DIR: ${CNPMCORE_NFS_DIR:-}
      CNPMCORE_NFS_OSS_ENDPOINT: ${CNPMCORE_NFS_OSS_ENDPOINT:-}
      CNPMCORE_NFS_OSS_BUCKET: ${CNPMCORE_NFS_OSS_BUCKET:-}
      CNPMCORE_NFS_OSS_ID: ${CNPMCORE_NFS_OSS_ID:-}
      CNPMCORE_NFS_OSS_SECRET: ${CNPMCORE_NFS_OSS_SECRET:-}

      TZ: ${TZ:-Asia/Shanghai}
    volumes:
      - ${CNPMCORE_STORAGE:-cnpm-storage}:/opt/cnpmcore
    ports:
      - ${EXPOSE_PORT:-7001}:7001
    networks:
      - cnpm-network
